### ISSUE TITLE
Documentation, Set up and Integration info, Screenshots missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/asksusi_messengers#15]
I think we are all aware what information has to go into a project documentation. Please include all necessary info and step by step info how to set it up for chat gateways (slack, facebook, gitter).

**Comment by shivenmian** [comment]
@mariobehling @sudheesh001 Check https://github.com/fossasia/asksusi_messengers/pull/17

**Comment by mariobehling** [comment]
https://github.com/fossasia/asksusi_messengers/pull/17#issuecomment-242638324

**Comment by sudheesh001** [comment]
taking over ! Will fix tonight
