### ISSUE TITLE
Slack instance not waking up on messaging

### ISSUE THREAD

**Issue by shivenmian** [fossasia/asksusi_messengers#16]
@sudheesh001 When I message Slack on asksusi.slack.com, it doesn't message me back right now. Is this because the Slack integration is just a script and not an app, and that I'll have to add routes to it to make it wake up when I message it?

When I messaged on the asksusi FB messenger bot though, it woke up. Is that purely because it's set up as an app and has a webhook? And I'll then have to convert mine too?

We need to get this done quickly, so that teams can add susi to their channels.

**Comment by shivenmian** [comment]
@sudheesh001 Still, the 18 hour keepalive limit of Heroku exists right?

We don't want the bot to be alive every second. What we want is the bot to come alive only when we message it. That's what's happening with the Messenger bot too. So probably for this, we need to set up the webhooks. What do you think?

**Comment by sudheesh001** [comment]
the library that you've utilized for `slackbots` doesn't have the webhook integration available in it. You'd have to include another library for `slack-node` which supports webhooks and from that call the required functions

**Comment by shivenmian** [comment]
@sudheesh001 Please check Gitter.

**Comment by shivenmian** [comment]
@sudheesh001 Wouldn't it work if I just wrapped my current code inside an app.post or something, like you did for the Messenger bot? Or will I have to use a different library?

**Comment by shivenmian** [comment]
@sudheesh001 @mariobehling Please check #18 and give feedback, I have tried to fix this issue.
