### ISSUE TITLE
Creating an AskSusi Slack bot

### ISSUE THREAD

**Issue by shivenmian** [fossasia/asksusi_messengers#8]
@mariobehling I'd like to create a Slack bot for AskSusi. I'll work on it on a different repo. Once it is made, we can just fork my repo, or I'll just work on a new repo asksusi_slack.

Once we have enough bots, we can integrate all of them in one single repository.

**Comment by sudheesh001** [comment]
I don't think this should be the approach, please use the same repository to add the other bots , we don't want bots to be built in multiple languages and then try integrate them

**Comment by shivenmian** [comment]
Ok, I'll add it here.

Tip: change repo name to "asksusi_bots" or something, rather than just messenger

**Comment by sudheesh001** [comment]
@mariobehling Can you suggest a name `asksusi_bots` or `asksusi_messengers` ?

**Comment by mariobehling** [comment]
Ok, agree. Just change it to `asksusi_messengers` then.

**Comment by mariobehling** [comment]
@sudheesh001 Please update the test integration to the changed name.

**Comment by mariobehling** [comment]
Documentation how to deploy it and how to add Susi to Slack is missing.

**Comment by shivenmian** [comment]
@mariobehling Check https://github.com/fossasia/asksusi_messengers/pull/17, also I think this issue is there in #15, so we can close this one.
